# Generated by Django 3.0.8 on 2021-07-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='price',
            field=models.TextField(blank=True),
        ),
    ]
