# Generated by Django 3.0.8 on 2021-07-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20210708_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='price',
            field=models.TextField(default='0'),
        ),
    ]
