# Generated by Django 3.0.8 on 2021-07-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20210708_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='price',
            field=models.TextField(default='1000'),
        ),
    ]
