# Generated by Django 3.0.8 on 2021-07-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20210708_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='price',
            field=models.TextField(null=True),
        ),
    ]
