# Generated by Django 3.0.8 on 2021-07-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20210708_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='price',
            field=models.TextField(blank=True),
        ),
    ]
