# Generated by Django 3.0.8 on 2021-07-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20210708_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='price',
        ),
    ]
